import json
import requests
import streamlit as st

st.set_page_config(page_title="My AI Chat", layout="wide")

st.title("My AI Chat")

# Load token from Streamlit secrets.
try:
    hf_token = st.secrets["HF_TOKEN"]
except Exception:
    hf_token = ""

if not hf_token:
    st.error(
        "Hugging Face token is missing. Add it to .streamlit/secrets.toml as HF_TOKEN."
    )
    st.stop()

model_id = "gpt2"
api_url = f"https://api-inference.huggingface.co/models/{model_id}"
headers = {"Authorization": f"Bearer {hf_token}"}

payload = {
    "inputs": "Hello!",
    "parameters": {"max_new_tokens": 60, "return_full_text": True},
}

with st.spinner("Contacting Hugging Face..."):
    try:
        resp = requests.post(api_url, headers=headers, json=payload, timeout=30)
    except requests.exceptions.RequestException as exc:
        st.error(f"Network error while contacting Hugging Face: {exc}")
        st.stop()

if resp.status_code != 200:
    msg = f"Hugging Face API error ({resp.status_code})."
    if resp.status_code in (401, 403):
        msg += " Invalid or missing token."
    elif resp.status_code == 429:
        msg += " Rate limit exceeded."
    elif resp.status_code >= 500:
        msg += " Server error from Hugging Face."

    # Try to extract error details from the response body.
    try:
        data = resp.json()
        if isinstance(data, dict) and data.get("error"):
            msg += f" Details: {data['error']}"
    except json.JSONDecodeError:
        pass

    st.error(msg)
    st.stop()

try:
    data = resp.json()
except json.JSONDecodeError:
    st.error("Unexpected response format from Hugging Face.")
    st.stop()

# Hugging Face text-generation responses are usually a list of dicts.
if isinstance(data, list) and data:
    generated = data[0].get("generated_text", "")
elif isinstance(data, dict) and data.get("generated_text"):
    generated = data.get("generated_text", "")
else:
    generated = ""

if not generated:
    st.error("No text was generated by the model.")
else:
    st.subheader("Model Response")
    st.write(generated)
